CUDA_VISIBLE_DEVICES=0 python main.py \
                       --dataset 'KITTI' \
                       --batchsize 32 \
                       --epochs 200 \
                       --workers_train 8 \
                       --workers_test 8 \
                       --learnrate 0.0001 \
                       --model DispNet \
                       --logdir 'tensorboard/finetune' \
                       --pth_name 'DispNetKITTI.pth' \
                       --maxdisp 192 \
                       --load_model './Vitis/build/float_model/DispNetSceneFlow.pth'
